### ISSUE TITLE
`:optional` kills the entire node

### ISSUE THREAD

**Issue by robertsteilberg** [Esri/adlib#37]
If I am trying to adlib something like this:
```
"url": "{{foo:optional}}/more/stuff/here"
```
and `foo` is falsey, then the resulting adlibbed variable `url` will be `undefined`, whereas I'd expect it to be `"/more/stuff/here"`.

**Comment by jgravois** [comment]
that's [_by design_](https://github.com/Esri/adlib#optional-transform).

`:optional` is a mechanism for templaters to insert a node if and only if a value is present.

**Comment by robertsteilberg** [comment]
Fair enough.
