### ISSUE TITLE
continuous testing

### ISSUE THREAD

**Issue by tomwayson** [Esri/adlib#4]
the current tests:
- execute in node on the bundled output
- have to be  manually re-run after changes to the code

I'd like to set up the tests to run whenever the code changes and to run on non-bundled output (i.e. something that would actually be used in a node app). I'm thinking something along the lines of what is discussed here: https://github.com/rollup/rollup/issues/657#issuecomment-220786674

**Comment by robertsteilberg** [comment]
@tomwayson I think this can be closed?

**Comment by tomwayson** [comment]
yep

https://github.com/Esri/adlib/blob/3da1637158aa5e0c9f0955dcab10696daa6ab95c/package.json#L13
